name: arxiv
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel

  # Utils
  - tqdm
  - h5py
  - networkx

  # Para tu flujo con notebooks y gr√°ficos
  - seaborn

  # Guaranteed compatible TF build via pip
  - pip:
      - tensorflow==2.15.0
      - tensorflow-hub==0.16.1
      - tensorflow-text==2.15.0
      - hnswlib==0.8.0
